# https://www.graphviz.org/


import networkx as nx
from networkx.drawing import nx_agraph
import pygraphviz as pgv


'''
The networkx.drawing.nx_agraph module only contains functions that provide an interface to the pygraphviz.agraph class, which is itself a Python
interface to Graphviz
- networkx.drawing.nx_agraph also contains functions that interface with Graphviz itself
- pygraphviz must also be installed
'''


def get_pygraphviz_graph_from_networkx_graph():
    g = nx.Graph([(1, 2), (7, 8), (2, 8)])
    pygraphviz_graph = nx_agraph.to_agraph(g)
    print(type(pygraphviz_graph)) # <class 'pygraphviz.agraph.AGraph'>
    print(pygraphviz_graph) # See terminal


def get_networkx_graph_from_pygraphviz_graph():
    '''It's annoying that NetworkX Graph objects only have a string representation based on the <Graph>.graph['name'] attribute'''
    g = nx.Graph([(1, 2), (7, 8), (2, 8)])
    g.graph['name'] = 'bar'
    pygraphviz_graph = nx_agraph.to_agraph(g)
    networkx_graph = nx_agraph.from_agraph(pygraphviz_graph)
    print(type(networkx_graph)) # <class 'networkx.classes.graph.Graph'>
    print(networkx_graph) # bar
    print(networkx_graph.edges()) # [('1', '2'), ('2', '8'), ('7', '8')]


def invoke_pygraphviz_layout():
    '''
    networkx.drawing.nx_agraph.graphviz_layout() is a wrapper for pygraphviz.agraph.AGraph.layout(). It returns a dictionary of x, y node positions
    for the nodes in the given graph
    - These are the available Graphviz layout programs:
        - neato (default): "spring model" layouts. Use for graphs with <100 nodes that I know nothing about. "Neato attemps to minimize a global
          energy function"
        - dot: directed graphs
        - fdp: "spring model" layouts. Different from neato because it reduces forces instead
        - sfdp: multiscale version of fdp for the layout of large graphs
        - twopi: radial layouts
        - circo: circular layout
    '''
    g = nx.Graph([(1, 2), (7, 8), (2, 8)])
    pos = nx_agraph.graphviz_layout(g) # prog='neato'
    print(pos) # {1: (27.0, 18.0), 2: (43.071, 88.469), 7: (32.966, 232.3), 8: (41.467, 160.69)}
    pos = nx_agraph.graphviz_layout(g, prog='circo')
    print(pos) # {1: (27.0, 18.0), 2: (153.0, 18.0), 7: (405.0, 18.0), 8: (279.0, 18.0)}


def inspect_pygraphviz_layout():
    '''
    These notes should be in an entirely separate pygraphviz workspace
    - pygraphviz is great for drawing graphs, but is NOT good for programatically building, modifying, and examining them. That's what NetworkX is
      good for
    '''
    # Create an equivalent pygraphviz graph and lay it out for comparison
    d = {1: {2: None}, 7: {8: None}, 2: {8: None}}
    pgv_graph = pgv.agraph.AGraph(d)
    print(type(pgv_graph)) # <class 'pygraphviz.agraph.AGraph'>
    # pygraphviz.agraph.Graph.layout() does not return anything. It modifies the graph
    x = pgv_graph.layout('neato')
    print(x) # None
    print(pgv_graph.nodes()) # ['1', '2', '7', '8']
    print(type(pgv_graph.nodes()[0])) # <class 'pygraphviz.agraph.Node'>
    print(pgv_graph.nodes()[0]) # 1
    # This is not helpful output
    print(type(pgv_graph.nodes()[0].attr)) # <class 'pygraphviz.agraph.ItemAttribute'>
    print(pgv_graph.nodes()[0].attr) # <pygraphviz.agraph.ItemAttribute object at 0x108e32cc0>
    for e in pgv_graph.nodes()[0].attr:
        print(e) # height\npos\nwidth
    # As I can FINALLY see, the nodes have EXACTLY the same positions as generated by the NetworkX interface above
    print(pgv_graph.nodes()[0].attr['pos']) # 27, 18
    print(pgv_graph.nodes()[1].attr['pos']) # 43.071, 88.469
    print(pgv_graph.nodes()[2].attr['pos']) # 41.467, 160.69
    print(pgv_graph.nodes()[3].attr['pos']) # 32.966, 232.3
    #pgv_graph.draw('/Users/austinchang/Desktop/testgraph.png')
    # draw() will not resolve ~ to the home directory (annoying)
    #pgv_graph.draw('~/Desktop/testgraph.png') # FileNotFoundError: [Errno 2] No such file or directory: '~/Desktop/testgraph.png'


if __name__ == '__main__':
    #get_pygraphviz_graph_from_networkx_graph()
    #get_networkx_graph_from_pygraphviz_graph()
    #invoke_pygraphviz_layout()
    inspect_pygraphviz_layout()
